routes/web.php
<?php

use App\Http\Controllers\AutocompleteController;
use App\Http\Controllers\BoardsController;
use App\Http\Controllers\CardsController;
use App\Http\Controllers\ChecklistsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ListsController;
use App\Http\Controllers\WorkspacesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function() {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('workspaces', WorkspacesController::class)->except('create', 'edit');
    Route::get('workspaces/{workspace}/members', [WorkspacesController::class, 'members'])->name('workspaces.members');
    Route::get('workspaces/{workspace}/boards', [WorkspacesController::class, 'boards'])->name('workspaces.boards');
    Route::post('workspaces/{workspace}/change-visibility', [WorkspacesController::class, 'changeVisibility'])->name('workspaces.changeVisibility');

    Route::get('autocomplete-search-workspace', [AutocompleteController::class, 'autocompleteWorkspace']);
    Route::get('autocomplete-search-board', [AutocompleteController::class, 'autocompleteBoard']);
    Route::get('autocomplete-search-card', [AutocompleteController::class, 'autocompleteCard']);
    Route::post('workspaces/{workspace}/invite-members', [WorkspacesController::class, 'inviteMembers'])->name('workspaces.inviteMembers');

    Route::post('workspaces/{workspace}/remove-member', [WorkspacesController::class, 'removeMember'])->name('workspaces.removeMember');
    Route::post('workspaces/{workspace}/leave-workspace', [WorkspacesController::class, 'leaveWorkspace'])->name('workspaces.leaveWorkspace');
    Route::post('workspaces/{workspace}/change-admin-status', [WorkspacesController::class, 'changeAdminStatus'])->name('workspaces.changeAdminStatus');

    Route::resource('boards', BoardsController::class)->except('create', 'edit', 'update', 'destroy');
    Route::post('boards/change-favourite-status', [BoardsController::class, 'changeFavouriteStatus'])->name('boards.changeFavouriteStatus');
    Route::post('boards/change-title', [BoardsController::class, 'changeTitle'])->name('boards.changeTitle');
    Route::post('boards/change-background', [BoardsController::class, 'changeBackground'])->name('boards.changeBackground');
    Route::post('boards/{board}/invite-members', [BoardsController::class, 'inviteMembers'])->name('boards.inviteMembers');
    Route::post('boards/lists/create', [ListsController::class, 'store'])->name('lists.store');
    Route::post('boards/lists/cards/create', [CardsController::class, 'store'])->name('cards.store');
    Route::post('boards/lists/cards/changeList', [CardsController::class, 'changeList'])->name('cards.changeList');
    Route::post('lists/change-name', [ListsController::class, 'changeName'])->name('lists.changeName');

    Route::post('cards/getCard', [CardsController::class, 'getCard'])->name('cards.getCard');
    Route::post('cards/change-name', [CardsController::class, 'changeName'])->name('cards.changeName');
    Route::post('cards/change-description', [CardsController::class, 'changeDescription'])->name('cards.changeDescription');
    Route::post('cards/change-duedate', [CardsController::class, 'changeDueDate'])->name('cards.changeDueDate');
    Route::post('cards/change-status', [CardsController::class, 'changeStatus'])->name('cards.changeStatus');
    Route::post('boards/{board}/cards/{card}/invite-members', [CardsController::class, 'inviteMembers'])->name('cards.inviteMembers');
    Route::post('cards/checklists/create', [ChecklistsController::class, 'store'])->name('checklists.store');
    Route::post('cards/checklists/change-status', [ChecklistsController::class, 'changeStatus'])->name('checklists.changeStatus');
    Route::post('cards/checklists/remove', [ChecklistsController::class, 'remove'])->name('checklists.remove');

    Route::post('cards/labels/create', [CardsController::class, 'createLabel'])->name('labels.store');
    Route::post('cards/labels/destroy', [CardsController::class, 'removeLabel'])->name('labels.destroy');
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function workspaces()
    {
        return $this->belongsToMany(Workspace::class)->withTimestamps();
    }

    public function boards()
    {
        return $this->belongsToMany(Board::class)->withPivot('favourite');
    }

    public function cards()
    {
        return $this->belongsToMany(Card::class);
    }

    // Accessor
    public function getAvatarAttribute()
    {
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }

    // Accessor
    public function getDefaultWorkspaceNameAttribute()
    {
        $workspace = $this->workspaces()->first();
        return $workspace->name;
    }

    // Model Event
    public static function boot()
    {
        parent::boot();
        static::created(function(User $user) {
            $workspace_name = $user->name . "'s Workspace";
            $workspace = Workspace::create([
                'name' => $workspace_name,
                'type' => 'Other',
                'visibility' => 'private',
            ]);
            $user->workspaces()->attach($workspace->id, ['admin' => 1]);
        });
    }

    public function getAdminStatusForWorkspace(Workspace $workspace)
    {
        return $this->workspaces()->where(['workspace_id' => $workspace->id, 'admin' => 1])->exists() ? 'admin' : 'normal';
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/css/bootstrap-select.min.css" integrity="sha512-ARJR74swou2y0Q2V9k0GbzQ/5vJ2RBSoCWokg4zkfM29Fb3vZEQyv0iWBMW/yvKgyHSR/7D64pFMmU8nYmbRkg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        .background-primary {
            background: #026AA7;
        }

        .navbar {
            padding: .2rem 1rem;
        }

        .my-font {
            font-family: 'IBM Plex Sans Arabic', sans-serif;
        }

        .btn-color {
            background-color: rgba(255, 255, 255, 0.3);
        }

        .navbar-collapse {
            flex-grow: 0;
        }

        .deco-none {
            color: inherit;
            text-decoration: inherit;
        }

        .deco-none:link {
            color: inherit;
            text-decoration: inherit;
        }

        .deco-none:hover {
            color: inherit;
            text-decoration: inherit;
        }

        .dropdown-item {
            display: flex;
            align-items: baseline;
        }

        .dropdown-item .text {
            display: flex !important;
            flex-direction: column;
        }

        .dropdown-item .text small {
            padding: 0 !important;
            margin-left: -20px;
        }

        .board-background-select:hover, .board-background-select:focus {
            outline: none;
        }

        #create-board-form input::placeholder {
            color: white;
        }

        .bootstrap-select .dropdown-toggle {
            background: #0079bf;
            color: white;
        }

        .shadow-sm {
            box-shadow: 0 .5rem 1rem rgba(0,0,0,.15)!important;
        }
    </style>

    @yield('page-level-styles')

</head>
<body>
    <div>
        @include('layouts.navigation')

        <!-- Page Content -->
        <main>
            @yield('main-content')
        </main>

        <!-- Jquery JS && Popper JS && Bootstrap JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/js/bootstrap-select.min.js" integrity="sha512-yDlE7vpGDP7o2eftkCiPZ+yuUyEcaBwoJoIhdXv71KZWugFqEphIS3PU60lEkFaz8RxaVsMpSvQxMBaKVwA5xg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="{{ asset('assets/plugins/jquery-validation/validation.min.js') }}"></script>
        <script src="{{ asset('assets/plugins/jquery-validation/additional-methods.min.js') }}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="{{ asset('js/app.js') }}"></script>

        @yield('page-level-scripts')

        @yield('broadcasting-scripts')

        @include('workspaces._create')

        @include('boards._create')

        <script>
            function RGBToHex(rgb) {
                let sep = rgb.indexOf(",") > -1 ? "," : " ";
                rgb = rgb.substr(4).split(")")[0].split(sep);
                let r = (+rgb[0]).toString(16),
                    g = (+rgb[1]).toString(16),
                    b = (+rgb[2]).toString(16);

                if (r.length == 1)
                    r = "0" + r;
                if (g.length == 1)
                    g = "0" + g;
                if (b.length == 1)
                    b = "0" + b;

                return "#" + r + g + b;
            }
        </script>
    </div>
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&display=swap" rel="stylesheet">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous">

        <style>
            .my-font {
                font-family: 'IBM Plex Sans Arabic', sans-serif;
            }

            .deco-none {
                color: inherit;
                text-decoration: inherit;
            }

            .deco-none:link {
                color: inherit;
                text-decoration: inherit;
            }

            .deco-none:hover {
                color: inherit;
                text-decoration: inherit;
            }

            .color-primary {
                color: #091e42;
            }

            .bg-shade {
                background: #eae6ff;
            }
        </style>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav class="navbar navbar-expand-lg background-primary d-flex justify-content-between">
    <div class="navbar-nav col-4 align-items-start ">
        <a href="{{ route('home') }}" class="btn btn-color deco-none">
            <i class="fa fa-home text-light" aria-hidden="true"></i>
        </a>
        <a href="{{ route("boards.index") }}" class="btn btn-color deco-none text-light ml-2">
            <i class="fa fa-trello text-light" aria-hidden="true"></i>
            Boards
        </a>
    </div>

    <div class="col-4 d-flex justify-content-center">
        <a href="{{ route('home') }}" class="deco-none my-font d-flex align-items-baseline mt-2">
            <i class="fa fa-trello mr-2 text-light fa-lg" aria-hidden="true"></i>
            <span class="h5 text-light font-weight-bold">Trello</span>
        </a>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="col-4 pr-0 d-flex justify-content-end">
        <div class="collapse navbar-collapse mr-2" id="navbarSupportedContent1">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    @auth
                        <a class="nav-link btn btn-color deco-none text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Create
                        </a>
                        <div class="dropdown-menu" style="width: 260px !important; left: -190px" aria-labelledby="navbarDropdown">
                            <div class="text-center pb-2 border-bottom">Create</div>
                            <div class="p-2 dropdown-item">
                                <a href="" class="deco-none d-flex flex-column" data-toggle="modal" data-target=".create-board-modal">
                                    <div>
                                        <i class="fa fa-trello mr-2" aria-hidden="true"></i>
                                        Create Board
                                    </div>
                                    <p class="mt-2 w-100" style="white-space: initial; font-size: 13px;">A board is made up of cards ordered on lists. Use it to manage projects, track information, or organize anything.</p>
                                </a>
                            </div>
                            <hr class="m-0">
                            <div class="p-2 dropdown-item">
                                <a href="" class="deco-none d-flex flex-column" data-toggle="modal" data-target=".create-workspace-modal">
                                    <div>
                                        <i class="fa fa-users mr-2" aria-hidden="true"></i>
                                        Create Workspace
                                    </div>
                                    <p class="mt-2 w-100" style="white-space: initial; font-size: 13px;">A Workspace is a group of boards and people. Use it to organize your company, side hustle, family, or friends.</p>
                                </a>
                            </div>
                        </div>
                    @endauth
                </li>
            </ul>
        </div>

        <a href="{{ route('home') }}" class="btn btn-color deco-none mr-2">
            <i class="fa fa-info-circle text-light" aria-hidden="true"></i>
        </a>

        <div class="d-flex justify-content-end">
            <div class="collapse navbar-collapse mr-2" id="navbarSupportedContent2">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        @auth
                            <a class="nav-link btn btn-color deco-none text-light" style="padding: 8px 12px !important;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-bell-o text-light" aria-hidden="true"></i>
                            </a>
                            <div class="dropdown-menu" style="width: 420px !important; left: -380px" aria-labelledby="navbarDropdown">
                                <div class="text-center pb-2 border-bottom">Notifications</div>
                                @if(auth()->user()->notifications()->count() == 0)
                                    <div class="mt-5 mb-5 d-flex align-items-center flex-column">
                                        <img src="{{ asset('images/notification.svg') }}" alt="No Notifications" class="img-fluid">
                                        <h3 class="mt-4">No Notifications</h3>
                                    </div>
                                @else
                                    <div class="p-2" style="overflow-y: auto; max-height: 400px;">
                                        @foreach($notifications as $notification)
                                            <div class="notification mt-3 mb-3">
                                                @if($notification->type === \App\Notifications\NewUserAddedToWorkspace::class)
                                                    You were added to new Workspace - <strong>{{ $notification->data['workspace']['name'] }}</strong>
                                                    <a href="{{ route('workspaces.show', $notification->data['workspace']['id']) }}" style="width: 35%;" class="btn mt-2 d-block background-primary btn-sm text-light deco-none">View Workspace</a>
                                                @elseif($notification->type === \App\Notifications\NewUserAddedToBoard::class)
                                                    You were added to new Board - <strong>{{ $notification->data['board']['title'] }}</strong>
                                                    <a href="{{ route('boards.show', $notification->data['board']['id']) }}" style="width: 35%;" class="btn mt-2 d-block background-primary btn-sm text-light deco-none">View Board</a>
                                                @elseif($notification->type === \App\Notifications\NewUserAddedToCard::class)
                                                    You were added to new Card - <strong>{{ $notification->data['card']['name'] }}</strong>
                                                    <a href="{{ route('boards.show', $notification->data['board']['id']) }}" style="width: 35%;" class="btn mt-2 d-block background-primary btn-sm text-light deco-none">View Card</a>
                                                @elseif($notification->type === \App\Notifications\CardDueDate::class)
                                                    Due Date is close of card - <strong>{{ $notification->data['card']['name'] }}</strong>
                                                    <a href="{{ route('boards.show', $notification->data['board']['id']) }}" style="width: 35%;" class="btn mt-2 d-block background-primary btn-sm text-light deco-none">View Card</a>
                                                @endif
                                            </div>
                                            <hr>
                                        @endforeach
                                    </div>
                                @endif
                            </div>
                        @endauth
                    </li>
                </ul>
            </div>
        </div>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    @auth
                        <a class="p-0 nav-link my-font" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{{ auth()->user()->avatar }}" alt="Avatar">
                        </a>
                        <div class="dropdown-menu" style="width: 260px !important; left: -205px" aria-labelledby="navbarDropdown">
                            <div class="text-center pb-2 border-bottom">Account</div>
                            <div class="d-flex pb-3 pt-3 pl-1 pr-1 border-bottom">
                                <img src="{{ auth()->user()->avatar }}" alt="Avatar" class="mr-3">
                                <div>
                                    <strong class="d-block">{{ auth()->user()->name }}</strong>
                                    <strong class="small font-weight-normal">{{ auth()->user()->email }}</strong>
                                </div>
                            </div>
                            <div class="border-bottom dropdown-item">
                                <a href="{{ route('home') }}" class="d-inline-block w-100 p-2" style="color: inherit; text-decoration:none;">Home</a>
                            </div>
                            <div class="border-bottom dropdown-item">
                                <a href="" class="d-inline-block w-100 p-2" style="color: inherit; text-decoration:none;">Cards</a>
                            </div>
                            <form action="{{ route('logout') }}" method="POST">
                                @csrf
                                <input type="submit" class="dropdown-item pt-2 pb-2" style="cursor: pointer; padding-left: 33px;" value="Logout">
                            </form>
                        </div>
                    @else
                        <a href="{{ route('login') }}" class="btn btn-sm btn-primary mr-3">Log in</a>
                        @if (Route::has('register'))
                            <a href="{{ route('register') }}" class="btn btn-sm btn-primary mr-3">Register</a>
                        @endif
                    @endauth
                </li>
            </ul>
        </div>
    </div>
</nav>