routes/web.php
<?php

use App\Http\Controllers\AutocompleteController;
use App\Http\Controllers\BoardsController;
use App\Http\Controllers\CardsController;
use App\Http\Controllers\ChecklistsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ListsController;
use App\Http\Controllers\WorkspacesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function() {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('workspaces', WorkspacesController::class)->except('create', 'edit');
    Route::get('workspaces/{workspace}/members', [WorkspacesController::class, 'members'])->name('workspaces.members');
    Route::get('workspaces/{workspace}/boards', [WorkspacesController::class, 'boards'])->name('workspaces.boards');
    Route::post('workspaces/{workspace}/change-visibility', [WorkspacesController::class, 'changeVisibility'])->name('workspaces.changeVisibility');

    Route::get('autocomplete-search-workspace', [AutocompleteController::class, 'autocompleteWorkspace']);
    Route::get('autocomplete-search-board', [AutocompleteController::class, 'autocompleteBoard']);
    Route::get('autocomplete-search-card', [AutocompleteController::class, 'autocompleteCard']);
    Route::post('workspaces/{workspace}/invite-members', [WorkspacesController::class, 'inviteMembers'])->name('workspaces.inviteMembers');

    Route::post('workspaces/{workspace}/remove-member', [WorkspacesController::class, 'removeMember'])->name('workspaces.removeMember');
    Route::post('workspaces/{workspace}/leave-workspace', [WorkspacesController::class, 'leaveWorkspace'])->name('workspaces.leaveWorkspace');
    Route::post('workspaces/{workspace}/change-admin-status', [WorkspacesController::class, 'changeAdminStatus'])->name('workspaces.changeAdminStatus');

    Route::resource('boards', BoardsController::class)->except('create', 'edit', 'update', 'destroy');
    Route::post('boards/change-favourite-status', [BoardsController::class, 'changeFavouriteStatus'])->name('boards.changeFavouriteStatus');
    Route::post('boards/change-title', [BoardsController::class, 'changeTitle'])->name('boards.changeTitle');
    Route::post('boards/change-background', [BoardsController::class, 'changeBackground'])->name('boards.changeBackground');
    Route::post('boards/{board}/invite-members', [BoardsController::class, 'inviteMembers'])->name('boards.inviteMembers');
    Route::post('boards/lists/create', [ListsController::class, 'store'])->name('lists.store');
    Route::post('boards/lists/cards/create', [CardsController::class, 'store'])->name('cards.store');
    Route::post('boards/lists/cards/changeList', [CardsController::class, 'changeList'])->name('cards.changeList');
    Route::post('lists/change-name', [ListsController::class, 'changeName'])->name('lists.changeName');

    Route::post('cards/getCard', [CardsController::class, 'getCard'])->name('cards.getCard');
    Route::post('cards/change-name', [CardsController::class, 'changeName'])->name('cards.changeName');
    Route::post('cards/change-description', [CardsController::class, 'changeDescription'])->name('cards.changeDescription');
    Route::post('cards/change-duedate', [CardsController::class, 'changeDueDate'])->name('cards.changeDueDate');
    Route::post('cards/change-status', [CardsController::class, 'changeStatus'])->name('cards.changeStatus');
    Route::post('boards/{board}/cards/{card}/invite-members', [CardsController::class, 'inviteMembers'])->name('cards.inviteMembers');
    Route::post('cards/checklists/create', [ChecklistsController::class, 'store'])->name('checklists.store');
    Route::post('cards/checklists/change-status', [ChecklistsController::class, 'changeStatus'])->name('checklists.changeStatus');
    Route::post('cards/checklists/remove', [ChecklistsController::class, 'remove'])->name('checklists.remove');

    Route::post('cards/labels/create', [CardsController::class, 'createLabel'])->name('labels.store');
    Route::post('cards/labels/destroy', [CardsController::class, 'removeLabel'])->name('labels.destroy');
});

require __DIR__.'/auth.php';

app/Models/Board.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Board extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function workspace()
    {
        return $this->belongsTo(Workspace::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function lists()
    {
        return $this->hasMany(Lists::class);
    }

    public function isFavourite()
    {
        if(auth()->user()->boards()->where('boards.id', $this->id)->exists()) {
            return auth()->user()->boards()->where('boards.id', $this->id)->first()->pivot->favourite;
        } else {
            return false;
        }
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function workspaces()
    {
        return $this->belongsToMany(Workspace::class)->withTimestamps();
    }

    public function boards()
    {
        return $this->belongsToMany(Board::class)->withPivot('favourite');
    }

    public function cards()
    {
        return $this->belongsToMany(Card::class);
    }

    // Accessor
    public function getAvatarAttribute()
    {
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }

    // Accessor
    public function getDefaultWorkspaceNameAttribute()
    {
        $workspace = $this->workspaces()->first();
        return $workspace->name;
    }

    // Model Event
    public static function boot()
    {
        parent::boot();
        static::created(function(User $user) {
            $workspace_name = $user->name . "'s Workspace";
            $workspace = Workspace::create([
                'name' => $workspace_name,
                'type' => 'Other',
                'visibility' => 'private',
            ]);
            $user->workspaces()->attach($workspace->id, ['admin' => 1]);
        });
    }

    public function getAdminStatusForWorkspace(Workspace $workspace)
    {
        return $this->workspaces()->where(['workspace_id' => $workspace->id, 'admin' => 1])->exists() ? 'admin' : 'normal';
    }
}

app/Http/Controllers/BoardsController.php
<?php

namespace App\Http\Controllers;

use App\Events\BoardEvent;
use App\Events\BoardUpdateEvent;
use App\Http\Requests\Boards\CreateBoardRequest;
use App\Models\Board;
use App\Models\User;
use App\Models\Workspace;
use App\Notifications\NewUserAddedToBoard;
use Carbon\Carbon;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class BoardsController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): View
    {
        $favourites = auth()->user()->boards()->where('favourite', 1)->get();
        $personalBoards = auth()->user()->boards()->whereDoesntHave('workspace')->get();
        $workspaces_ids = auth()->user()->boards()->where('workspace_id', '!=', null)->pluck('workspace_id', 'boards.id')->toArray();
        foreach($workspaces_ids as $key => $value) {
            if(! auth()->user()->workspaces()->where('workspaces.id', $value)->exists()) {
                $board = Board::find($key);
                $personalBoards->push($board);
            }
        }
        $workspaces = auth()->user()->workspaces()->with('boards')->get();
        return view("boards.index", compact(['personalBoards', 'workspaces', 'favourites']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBoardRequest $request)
    {
        if($request->has('workspace_id')) {
            $this->authorize('addBoard', Workspace::findOrFail($request->workspace_id));
        }
        $data = [
            'title' => $request->title,
            'background' => $request->background,
            'visibility' => $request->visibility,
        ];
        if($request->has('workspace_id')) {
            $data += ['workspace_id' => $request->workspace_id];
        }
        $board = Board::create($data);
        auth()->user()->boards()->attach($board->id, ['admin' => 1, 'viewed_at' => Carbon::now(), 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        session()->flash('success', 'Board Created Successfully!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Board  $board
     * @return \Illuminate\Http\Response
     */
    public function show(Board $board): View
    {
        $this->authorize('view', $board);
        auth()->user()->boards()->updateExistingPivot($board->id, ['viewed_at' => Carbon::now()]);
        $users = $board->users->take(5);
        $totalUsers = $board->users->count();
        $totalUsers -= $users->count();
        $lists = $board->lists()->with('cards')->get();
        $label_colors = ['#007bff', '#6c757d', '#28a745', '#ffc107', '#dc3545', '#343a40'];
        return view('boards.show', compact(['board', 'users', 'totalUsers', 'lists', 'label_colors']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Board  $board
     * @return \Illuminate\Http\Response
     */
    public function edit(Board $board)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Board  $board
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Board $board)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Board  $board
     * @return \Illuminate\Http\Response
     */
    public function destroy(Board $board)
    {
        //
    }

    public function changeFavouriteStatus(Request $request)
    {
        $favourite = preg_replace('/\s+/', '', $request->mark) == "n" ? 1 : 0;
        auth()->user()->boards()->updateExistingPivot($request->board_id, ['favourite' => $favourite]);
        return response()->json(['result' => $request->mark], 200);
    }

    public function changeTitle(Request $request)
    {
        $board = Board::findOrFail($request->board_id);
        $this->authorize('update', $board);
        $rules = [
            'newTitle' => 'required|max:255',
        ];
        $this->validate($request, $rules);
        if($request->newTitle == $board->title) {
            return response()->json(['result' => $request->board_id], 200);
        }
        $board->update([
            'title' => $request->newTitle,
        ]);
        BoardUpdateEvent::dispatch(['id' => $board->id, 'title' => $board->title, 'background' => $board->background, 'auth' => auth()->id()]);
        return response()->json(['result' => $request->board_id], 200);
    }

    public function changeBackground(Request $request)
    {
        $board = Board::findOrFail($request->board_id);
        $this->authorize('update', $board);
        $rules = [
            'newBackground' => 'required|in:#0079bf,#d29034,#519839,#b04632,#89609e,#cd5a91,#4bbf6b,#00aecc,#838c91',
        ];
        $this->validate($request, $rules);
        if($request->newBackground == $board->background) {
            return response()->json(['result' => $request->board_id, 'background' => $request->newBackground], 200);
        }
        $board->update([
            'background' => $request->newBackground,
        ]);
        BoardUpdateEvent::dispatch(['id' => $board->id, 'title' => $board->title, 'background' => $board->background, 'auth' => auth()->id()]);
        return response()->json(['result' => $request->board_id, 'background' => $request->newBackground], 200);
    }

    public function inviteMembers(Board $board, Request $request): RedirectResponse
    {
        $this->authorize('invite', $board);
        $users = $request->validate([
            'users' => 'required|array',
        ]);
        foreach($users as $user) {
            $board->users()->attach($user, ['admin' => 0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
            BoardEvent::dispatch(['id' => $user[0], 'auth' => auth()->id(), 'board_id' => $board->id, 'title' => $board->title, 'background' => $board->background, 'workspace_id' => $board->workspace_id, 'feature' => 'add']);
            $user = User::find($user[0]);
            $user->notify(new NewUserAddedToBoard($board));
        }
        return redirect()->back();
    }
}

resources/views/boards/_card.blade.php
<div class="modal fade card-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document" data-backdrop="static">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title">Card Details</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="d-flex">
                    <i class="fa fa-credit-card-alt mr-2" style="margin-top: 8px;" aria-hidden="true"></i>
                    <input id="card-name" type="text" name="card_name" class="form-control form-control-sm">
                </div>
                <p id="list-name" class="ml-4 pl-1 mt-1 mb-0"></p>
                <div class="d-flex mt-2">
                    <i class="fa fa-pencil-square-o mr-2" style="margin-top: 6px;" aria-hidden="true"></i>
                    <p class="m-0">Description</p>
                </div>
                <input id="card-description" type="text" name="card_description" class="form-control form-control-sm mt-2" placeholder="Add a more detailed description..." style="margin-left: 24px; width: 95%;">
                <hr>
                    <p class="mb-1 d-inline-block">Labels</p>
                    <div id="labels" class="mb-1"></div>
                    @can('update', $board)
                        <div class="dropdown">
                            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="label-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                            </button>
                            <div class="dropdown-menu" style="width: 300px; padding: 15px; background: #efefef;" aria-labelledby="label-dropdown">
                                <div class="text-center pb-2 border-bottom">Labels</div>
                                <input type="text" id="label-name" name="label-name" class="form-control form-control-sm">
                                @foreach($label_colors as $label_color)
                                    <button class="label-background-select" onClick="labelColorSelection(event, this)" style="border: 0; background: {{ $label_color }}; width: 260px; height: 30px; margin: 5px 5px 5px 5px;"></button>
                                @endforeach
                                <small class="label_error text-danger h6 d-block"></small>
                                <button class="btn btn-primary mt-1" id="create-label">Save</button>
                            </div>
                        </div>
                    @endcan
                <hr>
                <div class="mb-3">
                    <h5>Card Members</h5>
                    <div class="card-members"></div>
                </div>
                @can('update', $board)
                    <form action="" method="POST" id="invite-card-form">
                        @csrf
                        <div class="form-group @error('card_users') is-invalid @enderror">
                            <select name="card_users[]" id="card_users" class="form-control select2" multiple="multiple" data-error=".card_users_error"></select>
                            <small class="card_users_error text-danger h6"></small>
                            @error('card_users')
                                <small class="form-text text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-sm btn-success">Invite to Card</button>
                    </form>
                @endcan
                <hr>
                @can('update', $board)
                    <p class="mb-1 d-inline-block">Due Date</p>
                    <input type="checkbox" id="status" name="status" class="ml-1 form-check-input">
                    <input type="datetime-local" class="form-control" name="due_date" id="due_date">
                    <button class="btn btn-success btn-sm mt-2" id="due_date-save">Save</button>
                @endcan
                <hr>
                <p class="mb-1 d-inline-block">Checklists</p>
                <div id="checklists"></div>
                @can('update', $board)
                    <div class="d-flex">
                        <input type="text" class="form-control" name="checklist_item" id="checklist_item">
                        <button class="btn btn-success btn-sm mt-2 ml-2" id="add-checklist">Add an item</button>
                    </div>
                @endcan
            </div>
        </div>
    </div>
</div>

resources/views/boards/_create.blade.php
<div class="modal fade create-board-modal" tabindex="-1" role="dialog" aria-hidden="true" style="margin-left: 46%; transform: translateX(-50%);">
    <div class="modal-dialog modal-sm" role="document" data-backdrop="static">
        <div class="modal-content" style="background: transparent; border: 0;">
            <form action="{{ route('boards.store') }}" method="POST" autocomplete="off" id="create-board-form">
                @csrf
                <input type="hidden" name="background" id="background-attribute" value="#0079bf">
                <div style="position: absolute; left: 320px; height: 120px" id="backgrounds">
                    @foreach($board_backgrounds as $board_background)
                        <button class="board-background-select" style="border: 0; background: {{ $board_background }}; width: 30px; height: 30px; margin: 5px;
                            @if($loop->index == 3 || $loop->index == 4 || $loop->index == 5) position: relative; left: 40px; bottom: 120px @endif
                            @if($loop->index == 6 || $loop->index == 7 || $loop->index == 8) position: relative; left: 80px; bottom: 240px @endif"
                            onClick = "backgroundSelection(event, this)"
                        >
                        @if($loop->index == 0)
                            <i class='fa fa-check text-white' aria-hidden='true'></i>
                        @endif
                        </button>
                    @endforeach
                </div>
                <div class="modal-body" style="background: #0079bf;" id="board-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group d-inline-block">
                                <input
                                    type="text"
                                    class="form-control form-control-sm"
                                    id="title"
                                    name="title"
                                    value="{{ old('title') }}"
                                    placeholder="Add board title"
                                    style="background: transparent; color: white;">
                            </div>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>

                    @if(auth()->user()->workspaces()->count() != 0)
                        <select class="form-control form-control-sm" id="select-workspace" name="workspace_id" style="background: transparent; color: white;">
                            @foreach($workspaces as $workspace)
                                @if($workspace->name == auth()->user()->default_workspace_name)
                                    <option selected value="{{ $workspace->id }}" style="color: black;">{{ $workspace->name }}</option>
                                @else
                                    <option value="{{ $workspace->id }}" style="color: black;">{{ $workspace->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    @endif

                    <select class="form-control form-control-sm mt-3 selectpicker" name="visibility">
                        @foreach($board_visibility_types as $board_visibility_type)
                            @if($board_visibility_type == 'workspace' && auth()->user()->workspaces()->count() != 0)
                                <option selected data-icon="fa fa-users mr-1" data-subtext="All members of this Workspace can see and edit this board." value="{{ $board_visibility_type }}">{{ Str::ucfirst($board_visibility_type) }}</option>
                            @elseif($board_visibility_type == 'public')
                                <option data-icon="fa fa-globe mr-1" data-subtext="Anyone on the internet (including Google) can see this board. Only board members can edit." value="{{ $board_visibility_type}}">{{ Str::ucfirst($board_visibility_type) }}</option>
                            @elseif($board_visibility_type == 'private')
                                <option data-icon="fa fa-lock mr-1" data-subtext="Only board members can see and edit this board." value="{{ $board_visibility_type}}">{{ Str::ucfirst($board_visibility_type) }}</option>
                            @endif
                        @endforeach
                    </select>

                </div>
                <div class="modal-footer justify-content-start" style="border: 0; padding: 0">
                    <button type="submit" id="create-board-submit" class="btn btn-sm btn-light text-muted mt-3" style="cursor: not-allowed;">Create Board</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#create-board-submit').prop('disabled', true);
        $('#title').keyup(function() {
            if($('#title').val() == ""){
                $('#create-board-submit').attr('disabled', 'disabled');
                $('#create-board-submit')[0].style.cursor = "not-allowed";
                $('#create-board-submit').removeClass();
                $('#create-board-submit').addClass("btn btn-sm btn-light text-muted mt-3");
            }
            else{
                $('#create-board-submit').removeAttr('disabled');
                $('#create-board-submit')[0].style.cursor = "pointer";
                $('#create-board-submit').removeClass();
                $('#create-board-submit').addClass("btn btn-sm background-primary text-white mt-3");
            }
        });
    });
</script>

<script src="{{ asset('js/boards/create-validation.js') }}"></script>

<script>
    function backgroundSelection(event, element) {
        event.preventDefault();
        $("#backgrounds button").each(function() {
            $(this).text("");
        });
        element.innerHTML = "<i class='fa fa-check text-white' aria-hidden='true'></i>";
        let color = RGBToHex(element.style.background);
        $("#board-body").css('background', color);
        $(".bootstrap-select .dropdown-toggle").css('background', color);
        $("#background-attribute").val(color);
    }
</script>

<script>
    @error('title')
        $('.create-board-modal').modal('show');
    @enderror
    @error('background')
        $('.create-board-modal').modal('show');
    @enderror
    @error('visibility')
        $('.create-board-modal').modal('show');
    @enderror
    @error('workspace_id')
        $('.create-board-modal').modal('show');
    @enderror
</script>

resources/views/boards/_invite.blade.php
<div class="modal fade invite-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document" data-backdrop="static">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Invite to board</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="row p-3">
                <div class="col-12">
                    <form action="{{ route('boards.inviteMembers', $board->id) }}" method="POST" id="invite-form">
                        @csrf
                        <div class="form-group @error('users') is-invalid @enderror">
                            <select name="users[]" id="users" class="form-control select2" multiple="multiple" data-error=".users_error"></select>
                            <small class="users_error text-danger h6"></small>
                            @error('users')
                                <small class="form-text text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-sm btn-success">Invite to Board</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>