routes/web.php
<?php

use App\Http\Controllers\AutocompleteController;
use App\Http\Controllers\BoardsController;
use App\Http\Controllers\CardsController;
use App\Http\Controllers\ChecklistsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ListsController;
use App\Http\Controllers\WorkspacesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function() {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('workspaces', WorkspacesController::class)->except('create', 'edit');
    Route::get('workspaces/{workspace}/members', [WorkspacesController::class, 'members'])->name('workspaces.members');
    Route::get('workspaces/{workspace}/boards', [WorkspacesController::class, 'boards'])->name('workspaces.boards');
    Route::post('workspaces/{workspace}/change-visibility', [WorkspacesController::class, 'changeVisibility'])->name('workspaces.changeVisibility');

    Route::get('autocomplete-search-workspace', [AutocompleteController::class, 'autocompleteWorkspace']);
    Route::get('autocomplete-search-board', [AutocompleteController::class, 'autocompleteBoard']);
    Route::get('autocomplete-search-card', [AutocompleteController::class, 'autocompleteCard']);
    Route::post('workspaces/{workspace}/invite-members', [WorkspacesController::class, 'inviteMembers'])->name('workspaces.inviteMembers');

    Route::post('workspaces/{workspace}/remove-member', [WorkspacesController::class, 'removeMember'])->name('workspaces.removeMember');
    Route::post('workspaces/{workspace}/leave-workspace', [WorkspacesController::class, 'leaveWorkspace'])->name('workspaces.leaveWorkspace');
    Route::post('workspaces/{workspace}/change-admin-status', [WorkspacesController::class, 'changeAdminStatus'])->name('workspaces.changeAdminStatus');

    Route::resource('boards', BoardsController::class)->except('create', 'edit', 'update', 'destroy');
    Route::post('boards/change-favourite-status', [BoardsController::class, 'changeFavouriteStatus'])->name('boards.changeFavouriteStatus');
    Route::post('boards/change-title', [BoardsController::class, 'changeTitle'])->name('boards.changeTitle');
    Route::post('boards/change-background', [BoardsController::class, 'changeBackground'])->name('boards.changeBackground');
    Route::post('boards/{board}/invite-members', [BoardsController::class, 'inviteMembers'])->name('boards.inviteMembers');
    Route::post('boards/lists/create', [ListsController::class, 'store'])->name('lists.store');
    Route::post('boards/lists/cards/create', [CardsController::class, 'store'])->name('cards.store');
    Route::post('boards/lists/cards/changeList', [CardsController::class, 'changeList'])->name('cards.changeList');
    Route::post('lists/change-name', [ListsController::class, 'changeName'])->name('lists.changeName');

    Route::post('cards/getCard', [CardsController::class, 'getCard'])->name('cards.getCard');
    Route::post('cards/change-name', [CardsController::class, 'changeName'])->name('cards.changeName');
    Route::post('cards/change-description', [CardsController::class, 'changeDescription'])->name('cards.changeDescription');
    Route::post('cards/change-duedate', [CardsController::class, 'changeDueDate'])->name('cards.changeDueDate');
    Route::post('cards/change-status', [CardsController::class, 'changeStatus'])->name('cards.changeStatus');
    Route::post('boards/{board}/cards/{card}/invite-members', [CardsController::class, 'inviteMembers'])->name('cards.inviteMembers');
    Route::post('cards/checklists/create', [ChecklistsController::class, 'store'])->name('checklists.store');
    Route::post('cards/checklists/change-status', [ChecklistsController::class, 'changeStatus'])->name('checklists.changeStatus');
    Route::post('cards/checklists/remove', [ChecklistsController::class, 'remove'])->name('checklists.remove');

    Route::post('cards/labels/create', [CardsController::class, 'createLabel'])->name('labels.store');
    Route::post('cards/labels/destroy', [CardsController::class, 'removeLabel'])->name('labels.destroy');
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function workspaces()
    {
        return $this->belongsToMany(Workspace::class)->withTimestamps();
    }

    public function boards()
    {
        return $this->belongsToMany(Board::class)->withPivot('favourite');
    }

    public function cards()
    {
        return $this->belongsToMany(Card::class);
    }

    // Accessor
    public function getAvatarAttribute()
    {
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }

    // Accessor
    public function getDefaultWorkspaceNameAttribute()
    {
        $workspace = $this->workspaces()->first();
        return $workspace->name;
    }

    // Model Event
    public static function boot()
    {
        parent::boot();
        static::created(function(User $user) {
            $workspace_name = $user->name . "'s Workspace";
            $workspace = Workspace::create([
                'name' => $workspace_name,
                'type' => 'Other',
                'visibility' => 'private',
            ]);
            $user->workspaces()->attach($workspace->id, ['admin' => 1]);
        });
    }

    public function getAdminStatusForWorkspace(Workspace $workspace)
    {
        return $this->workspaces()->where(['workspace_id' => $workspace->id, 'admin' => 1])->exists() ? 'admin' : 'normal';
    }
}

app/Models/Workspace.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Workspace extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function users()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function boards()
    {
        return $this->hasMany(Board::class);
    }
}

app/Http/Controllers/WorkspacesController.php
<?php

namespace App\Http\Controllers;

use App\Events\WorkspaceEvent;
use App\Events\WorkspaceUpdateEvent;
use App\Http\Requests\Workspaces\CreateWorkspaceRequest;
use App\Http\Requests\Workspaces\UpdateWorkspaceRequest;
use App\Models\User;
use App\Models\Workspace;
use App\Notifications\NewUserAddedToWorkspace;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class WorkspacesController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateWorkspaceRequest $request): RedirectResponse
    {
        $workspace = Workspace::create([
            'name' => $request->name,
            'type' => $request->type,
            'description' => $request->description,
            'visibility' => 'private',
        ]);
        $workspace->users()->attach(auth()->id(), ['admin' => 1]);
        session()->flash('success', 'Workspace Created Successfully!');
        return redirect(route('workspaces.show', $workspace));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Workspace  $workspace
     * @return \Illuminate\Http\Response
     */
    public function show(Workspace $workspace): View
    {
        $this->authorize('view', $workspace);
        return view('workspaces.show', compact(['workspace']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Workspace  $workspace
     * @return \Illuminate\Http\Response
     */
    public function edit(Workspace $workspace)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Workspace  $workspace
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateWorkspaceRequest $request, Workspace $workspace): RedirectResponse
    {
        $this->authorize('update', $workspace);
        $workspace->update([
            'name' => $request->name,
            'type' => $request->type,
            'description' => $request->description,
        ]);
        WorkspaceUpdateEvent::dispatch(['auth' => auth()->id(), 'name' => $workspace->name, 'workspace_id' => $workspace->id, 'description' => $workspace->description, 'type' => $workspace->type, 'visibility' => $workspace->visibility]);
        session()->flash('success', 'Workspace Updated Successfully!');
        return redirect(route('workspaces.show', $workspace));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Workspace  $workspace
     * @return \Illuminate\Http\Response
     */
    public function destroy(Workspace $workspace)
    {
        $this->authorize('delete', $workspace);
        $members = $workspace->users;
        foreach($members as $member) {
            WorkspaceEvent::dispatch(['id' => $member->id, 'auth' => auth()->id(), 'name' => $workspace->name, 'workspace_id' => $workspace->id, 'description' => $workspace->description, 'type' => $workspace->type, 'visibility' => $workspace->visibility, 'feature' => 'destroy']);
        }
        $workspace->delete();
        session()->flash('success', 'Workspace Deleted Successfully!');
        return redirect(route('home'));
    }

    public function members(Workspace $workspace): View
    {
        $this->authorize('view', $workspace);
        $users = $workspace->users;
        return view('workspaces._members', compact(['workspace', 'users']));
    }

    public function boards(Workspace $workspace): View
    {
        $this->authorize('view', $workspace);
        $boards = $workspace->boards;
        return view('workspaces._boards', compact(['workspace', 'boards']));
    }

    public function changeVisibility(Workspace $workspace, Request $request)
    {
        $workspace->update([
            'visibility' => $request->visibility,
        ]);
        WorkspaceUpdateEvent::dispatch(['auth' => auth()->id(), 'name' => $workspace->name, 'workspace_id' => $workspace->id, 'description' => $workspace->description, 'type' => $workspace->type, 'visibility' => $workspace->visibility]);
        return response()->json(['visibility' => $request->visibility], 200);
    }

    public function inviteMembers(Workspace $workspace, Request $request): RedirectResponse
    {
        $members = $request->validate([
            'members' => 'required|array',
        ]);
        foreach($members as $member) {
            $workspace->users()->attach($member, ['admin' => 0]);
            WorkspaceEvent::dispatch(['id' => $member[0], 'auth' => auth()->id(), 'name' => $workspace->name, 'workspace_id' => $workspace->id, 'description' => $workspace->description, 'type' => $workspace->type, 'visibility' => $workspace->visibility, 'feature' => 'add']);
            $user = User::find($member[0]);
            $user->notify(new NewUserAddedToWorkspace($workspace));
        }
        // event(new WorkspaceEvent(['id' => $member[0], 'auth' => auth()->id(), 'name' => $workspace->name, 'workspace_id' => $workspace->id, 'description' => $workspace->description, 'type' => $workspace->type, 'visibility' => $workspace->visibility, 'feature' => 'add']));
        session()->flash('success', count($request->members) > 1 ? 'Members Added To Workspace Successfully!' : 'Member Added To Workspace Successfully!');
        return redirect()->back();
    }

    public function removeMember(Workspace $workspace, Request $request)
    {
        $this->authorize('removeMember', $workspace);
        $workspace->users()->detach($request->user_id);
        WorkspaceEvent::dispatch(['id' => $request->user_id, 'auth' => auth()->id(), 'name' => $workspace->name, 'workspace_id' => $workspace->id, 'description' => $workspace->description, 'type' => $workspace->type, 'visibility' => $workspace->visibility, 'feature' => 'remove']);
        return response()->json(['result' => $request->user_id], 200);
    }

    public function leaveWorkspace(Workspace $workspace)
    {
        $workspace->users()->detach(auth()->id());
        session()->flash('success', 'Workspace Left Successfully!');
        return redirect(route('home'));
    }

    public function changeAdminStatus(Workspace $workspace, Request $request)
    {
        $this->authorize('changeAdminStatus', $workspace);
        if(auth()->id() == $request->user_id) {
            return response()->json(['status' => 401], 401);
        }
        $workspace->users()->updateExistingPivot($request->user_id, ['admin' => $request->adminStatus]);
        return response()->json(['result' => $request->adminStatus], 200);
    }
}

resources/views/workspaces/_boards.blade.php
@extends('workspaces.show')

@section('workspace-content')
    <div>
        <div class="favourites">
            @if(! $boards->isEmpty())
                <h5 class="mb-3">
                    <i class="fa fa-user mr-2"></i>
                    Your Workspace Boards
                </h5>
                <div class="d-flex justify-content-start align-items-center flex-wrap mt-4 mb-4 favs" style="gap: 10px;">
                    @foreach($boards as $board)
                        <a href="{{ route('boards.show', $board->id) }}" style="background: {{ $board->background }}; height: 100px; width: 180px;" class="deco-none rounded board @if(! $board->isFavourite()) fav @endif">
                            <h5 class="ml-2 mt-2 text-white">{{ $board->title }}</h5>
                            @if($board->isFavourite() == 1)
                                <span>
                                    <i class="fa fa-star text-warning float-right star" style="position: relative; top: 38px; left: -10px;" aria-hidden="true" data-star="y" data-id="{{ $board->id }}"></i>
                                </span>
                            @else
                                <span class="d-none">
                                    <i class="fa fa-star-o text-warning float-right star" style="position: relative; top: 38px; left: -10px;" aria-hidden="true" data-star="n" data-id="{{ $board->id }}"></i>
                                </span>
                            @endif
                        </a>
                    @endforeach
                    @can('addBoard', $workspace)
                        <button id="create-board" onClick="selectOption('{{ $workspace->id }}')" style="height: 100px; width: 180px;" class="rounded btn btn-light" data-toggle="modal" data-target=".create-board-modal">
                            <p class="m-0 text-dark">Create new board</p>
                        </button>
                    @endcan
                </div>
            @else
                <div class="row shadow-sm pt-2 pb-2 m-0">
                    <div class="col-md-3">
                        <img src="{{ asset('images/workspace.svg') }}" alt="">
                    </div>
                    <div class="col-md-9">
                        <p class="h6 mt-4">Welcome to the Workspace!</p>
                        <p>This workspace contains no boards!</p>
                    </div>
                </div>
                @can('addBoard', $workspace)
                    <button id="create-board" onClick="selectOption('{{ $workspace->id }}')" style="height: 100px; width: 180px;" class="rounded btn btn-light mt-4" data-toggle="modal" data-target=".create-board-modal">
                        <p class="m-0 text-dark">Create new board</p>
                    </button>
                @endcan
            @endif
        </div>
    </div>
@endsection

@section('page-level-script')
    <script>
        function selectOption(workspace_id) {
            $("#select-workspace").val(workspace_id);
        }
    </script>

    <script>
        $(document).on("mouseenter", ".board", function() {
            $(this).css('cursor', 'pointer');
            if($(this).hasClass('fav')) {
                $(this).children().last().removeClass("d-none");
            }
        });

        $(document).on("mouseleave", ".board", function() {
            $(this).css('cursor', 'default');
            if($(this).hasClass('fav')) {
                $(this).children().last().addClass("d-none");
            }
        });
    </script>

    <script>
        $(".star").click(function(e) {
            e.preventDefault();
            let id = $(this).data("id");
            let mark = $(this).data("star");
            $.ajax({
                type: 'POST',
                url: `{{ route('boards.changeFavouriteStatus') }}`,
                data: {_token: '{{ csrf_token() }}', 'board_id': id, 'mark': mark },
                success: function(data) {
                    if(data) {
                        if(mark.includes("n")) {
                            $(`.board [data-id=${id}]`).attr("data-star", "y");
                            $(`.board [data-id=${id}]`).data("star", "y");
                            $(`.board [data-id=${id}]`).removeClass("fa-star-o");
                            $(`.board [data-id=${id}]`).addClass("fa-star");
                            $(`.board [data-id=${id}]`).parent().removeClass("d-none");
                            $(`.board [data-id=${id}]`).parent().parent().removeClass("fav");
                            $(`.board [data-id=${id}]`).parent().parent().off();
                        } else {
                            $(`.board [data-id=${id}]`).attr("data-star", "n");
                            $(`.board [data-id=${id}]`).data("star", "n");
                            $(`.board [data-id=${id}]`).removeClass("fa-star");
                            $(`.board [data-id=${id}]`).addClass("fa-star-o");
                            $(`.board [data-id=${id}]`).parent().addClass("d-none");
                            $(`.board [data-id=${id}]`).parent().parent().addClass("fav");
                            $(`.board [data-id=${id}]`).parent().parent().bind({
                                mouseenter: function() {
                                    $(this).children().last().removeClass("d-none");
                                    $(this).css('cursor', 'pointer');
                                },
                                mouseleave: function() {
                                    $(this).children().last().addClass("d-none");
                                    $(this).css('cursor', 'default');
                                }
                            });
                        }
                    }
                },
                error: function(data) {
                    if(data.status == 401 || data.status == 403) {
                        let url = "{{ route('home') }}";
                        document.location.href = url;
                    }
                }
            });
        });
    </script>

    <script>
        var auth = {{ auth()->id() }};
        var boards = {{ json_encode(auth()->user()->boards()->where('boards.workspace_id', $workspace->id)->pluck('boards.id')->toArray()) }};
        for(var i = 0; i < boards.length; i++) {
            Echo.private(`board-update.${boards[i]}`)
                .listen('BoardUpdateEvent', (e) => {
                    if(auth != e.board.auth) {
                        $(`.favs [data-id=${e.board.id}]`).parent().siblings("h5").text(e.board.title);
                        $(`.favs [data-id=${e.board.id}]`).parent().parent().css('background-color', e.board.background);
                    }
                });
        }

        Echo.private(`board.${auth}`)
            .listen('BoardEvent', (e) => {
                let workspace_id = e.board.workspace_id;
                if(e.board.feature == "add") {
                    if(workspace_id == {{ $workspace->id }}) {
                        $("#create-board").before(`
                            <a href="/boards/${e.board.board_id}" style="background: ${e.board.background}; height: 100px; width: 180px;" class="deco-none rounded board fav">
                                <h5 class="ml-2 mt-2 text-white">${e.board.title}</h5>
                                <span class="d-none">
                                    <i class="fa fa-star-o text-warning float-right star" style="position: relative; top: 38px; left: -10px;" aria-hidden="true" data-star="n" data-id="${e.board.board_id}"></i>
                                </span>
                            </a>
                        `);
                    }
                }
            });
    </script>
@endsection

resources/views/workspaces/_create.blade.php
<div class="modal fade create-workspace-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document" data-backdrop="static">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Let's build a Workspace</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p class="pl-3 pt-2">Boost your productivity by making it easier for everyone to access boards in one location.</p>
                </div>
            </div>
            <form action="{{ route('workspaces.store') }}" method="POST" id="create-workspace-form">
                @csrf
                <div class="modal-body">
                    <div class="form-group pb-2 @error('name') is-invalid @enderror">
                        <label for="name">Workspace name</label>
                        <input
                            type="text"
                            class="form-control"
                            id="name"
                            name="name"
                            value="{{ old('name') }}"
                            placeholder="Taco's Co."
                            data-error=".name_error">
                        <small class="d-block">This is the name of your company, team or organization.</small>
                        @error('name')
                            <small class="form-text text-danger">{{ $message }}</small>
                        @enderror
                        <small class="name_error text-danger h6"></small>
                    </div>

                    <div class="form-group pb-2 @error('type') is-invalid @enderror">
                        <label for="type">Workspace type</label>
                        <select name="type" id="type" class="form-control">
                            <option value="">Choose...</option>
                            @foreach($workspace_types as $workspace_type)
                                <option value="{{ $workspace_type }}">{{ $workspace_type }}</option>
                            @endforeach
                        </select>
                        @error('type')
                            <small class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="form-group @error('description') is-invalid @enderror">
                        <label for="description">Workspace description <span class="font-weight-light">Optional</span></label>
                        <input
                            type="text"
                            class="form-control"
                            id="description"
                            name="description"
                            value="{{ old('description') }}"
                            placeholder="Our team organizes everything here."
                            data-error=".description_error">
                        <small>Get your members on board with a few words about your Workspace.</small>
                        @error('description')
                            <small class="form-text text-danger">{{ $message }}</small>
                        @enderror
                        <small class="description_error text-danger h6"></small>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="{{ asset('js/workspaces/create-validation.js') }}"></script>

<script>
    @error('name')
        $('.create-workspace-modal').modal('show');
    @enderror
    @error('description')
        $('.create-workspace-modal').modal('show');
    @enderror
    @error('type')
        $('.create-workspace-modal').modal('show');
    @enderror
</script>

resources/views/workspaces/_delete.blade.php
<!-- Modal -->
<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Workspace</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('workspaces.destroy', $workspace->id) }}" method="POST" id="deleteWorkspaceForm">
                @csrf
                @method("DELETE")
                <div class="modal-body">
                    Deleting a Workspace is permanent. Are you sure you want to delete this Workspace? There is no undo. Boards with this Workspace won't be deleted. Your boards in this Workspace will appear in your personal boards list.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/workspaces/_edit.blade.php
<div class="modal fade edit-workspace-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document" data-backdrop="static">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Your Workspace</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('workspaces.update', $workspace->id) }}" method="POST" id="edit-workspace-form">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <div class="form-group pb-2 @error('name') is-invalid @enderror">
                        <label for="name">Workspace name</label>
                        <input
                            type="text"
                            class="form-control"
                            id="name"
                            name="name"
                            value="{{ old('name', $workspace->name) }}"
                            placeholder="Taco's Co."
                            data-error=".name_error">
                        @error('name')
                            <small class="form-text text-danger">{{ $message }}</small>
                        @enderror
                        <small class="name_error text-danger h6"></small>
                    </div>

                    <div class="form-group pb-2 @error('type') is-invalid @enderror">
                        <label for="type">Workspace type</label>
                        <select name="type" id="type" class="form-control">
                            <option value="">Choose...</option>
                            @foreach($workspace_types as $workspace_type)
                                @if($workspace_type == old('type', $workspace->type))
                                    <option value="{{ $workspace_type }}" selected>{{ $workspace_type }}</option>
                                @else
                                    <option value="{{ $workspace_type }}">{{ $workspace_type }}</option>
                                @endif
                            @endforeach
                        </select>
                        @error('type')
                            <small class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="form-group @error('description') is-invalid @enderror">
                        <label for="description">Workspace description <span class="font-weight-light">Optional</span></label>
                        <input
                            type="text"
                            class="form-control"
                            id="description"
                            name="description"
                            value="{{ old('description', $workspace->description) }}"
                            placeholder="Our team organizes everything here."
                            data-error=".description_error">
                        @error('description')
                            <small class="form-text text-danger">{{ $message }}</small>
                        @enderror
                        <small class="description_error text-danger h6"></small>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>